kind: pipeline
type: docker
name: kleio-deploy

steps:
  - name: build-image
    image: docker:24-dind
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    commands:
      - docker build -t kleio:latest .
      
  - name: deploy
    image: docker:24-cli
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    commands:
      - apk add --no-cache docker-compose
      - docker-compose -f docker-compose.prod.yml down || true
      - docker network create kleio-network || true
      - docker-compose -f docker-compose.prod.yml up -d
    when:
      branch:
        - main
      event:
        - push
    depends_on:
      - build-image

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock
