---
kind: pipeline
type: docker
name: build

steps:
  - name: build-frontend
    image: node:22-alpine
    environment:
      NODE_ENV: production
    commands:
      - cd clio
      - npm install --include=dev
      - npm run build

  - name: build-backend
    image: golang:1.25-alpine
    commands:
      - go mod download
      - go build -o kleio cmd/api/main.go
    depends_on:
      - build-frontend

  - name: build-docker-image
    image: docker:24-cli
    commands:
      - docker build -t kleio:latest .
    depends_on:
      - build-backend

---
kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy
    image: docker/compose:alpine-1.29.2
    commands:
      - docker-compose -f docker-compose.prod.yml down || true
      - docker network create kleio-network || true
      - docker-compose -f docker-compose.prod.yml up -d
    when:
      branch:
        - main
      event:
        - push

depends_on:
  - build
