kind: pipeline
type: docker
name: kleio-deploy

steps:
  - name: build-image
    image: plugins/docker
    settings:
      repo: kleio
      tags: latest
      dockerfile: Dockerfile
      context: .
      storage_driver: vfs
      
  - name: deploy
    image: docker/compose:alpine-1.29.2
    commands:
      - docker-compose -f docker-compose.prod.yml down || true
      - docker network create kleio-network || true
      - docker-compose -f docker-compose.prod.yml up -d
    when:
      branch:
        - main
      event:
        - push
    depends_on:
      - build-image
