services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "38080:38080"
    environment:
      - APP_ENV=production
    volumes:
      - kleio_data:/data/db
    restart: unless-stopped

volumes:
  kleio_data:
    driver: local
