version: "3.8"

networks:
  kleio-network:

services:
  app:
    image: deadstyle/kleio:latest
    ports:
      - "38080:38080"
    environment:
      - APP_ENV=production
      - APP_PORT=38080
    volumes:
      - ~/kleio_data:/data/db
    restart: unless-stopped
    networks:
      - kleio-network
