version: "3.8"

networks:
  traefik:
    external: true
  kleio-network:
    external: true

services:
  kleio:
    image: deadstyle/kleio:latest
    container_name: kleio
    restart: unless-stopped
    networks:
      - traefik
      - kleio-network
    volumes:
      - "/mnt/server/kleio_data:/data/db"
    ports:
      - "38080:38080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:38080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
