-- Seed data for PostgreSQL multi-user Kleio
-- This migration adds initial reference data and default user

-- Insert common stylus models (base models that users can reference)
-- Note: These will be created as base models that users can copy/reference
-- but each user will have their own stylus records

-- Common genres
INSERT INTO genres (name) VALUES
('Electronic'),
('Rock'),
('Hip Hop'),
('Jazz'),
('Classical'),
('Pop'),
('Folk'),
('Reggae'),
('Blues'),
('Country'),
('Funk / Soul'),
('Latin'),
('Stage & Screen'),
('Children''s'),
('Non-Music')
ON CONFLICT (name) DO NOTHING;

-- Common styles
INSERT INTO styles (name) VALUES
('House'),
('Techno'),
('Ambient'),
('Drum n Bass'),
('Dubstep'),
('Trance'),
('Progressive House'),
('Deep House'),
('Minimal'),
('Electro'),
('IDM'),
('Breakbeat'),
('Garage'),
('UK Garage'),
('2-Step'),
('Abstract'),
('Experimental'),
('Downtempo'),
('Trip Hop'),
('Leftfield'),
('Alternative Rock'),
('Indie Rock'),
('Punk'),
('Hardcore'),
('Metal'),
('Hard Rock'),
('Progressive Rock'),
('Psychedelic Rock'),
('Blues Rock'),
('Folk Rock'),
('Boom Bap'),
('Conscious'),
('Gangsta'),
('Trap'),
('Old School'),
('Contemporary Jazz'),
('Bebop'),
('Cool Jazz'),
('Free Jazz'),
('Fusion'),
('Smooth Jazz'),
('Vocal Jazz'),
('Swing'),
('Big Band'),
('Contemporary Classical'),
('Modern Classical'),
('Baroque'),
('Romantic'),
('Chamber Music'),
('Symphony'),
('Opera'),
('Pop Rock'),
('Synth-pop'),
('Dance-pop'),
('Teen Pop'),
('Contemporary Folk'),
('Traditional Folk'),
('Folk Blues'),
('Acoustic'),
('Roots Reggae'),
('Dub'),
('Dancehall'),
('Ragga'),
('Delta Blues'),
('Chicago Blues'),
('Electric Blues'),
('Country Rock'),
('Bluegrass'),
('Honky Tonk'),
('Contemporary Country'),
('Funk'),
('Soul'),
('Neo Soul'),
('Disco'),
('R&B'),
('Motown'),
('Bossa Nova'),
('Samba'),
('Salsa'),
('Tango'),
('Flamenco'),
('Musical'),
('Soundtrack'),
('Score'),
('Dialogue')
ON CONFLICT (name) DO NOTHING;

-- Note: We don't create a default user here as that should be done during first-time setup
-- or user registration process. The application should handle creating the first user
-- when someone accesses the system for the first time.